# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

google-ID: 'UA-112060364-2'

menu:
# - {name: 'Interesting Facts', folder: 'pages', file: 'facts.html'}
# - {name: 'Learning Resources', folder: 'pages', file: 'resources.html'}
- {name: 'Posts', folder: '.', file: 'posts'}
- {name: 'Photos', folder: '.', file: 'photos'}
- {name: 'Albums', folder: '.', file: 'albums'}
- {name: 'About', folder: '.', file: 'about'}
# - {name: 'Sample', folder: '.', file: 'sample'}
# - {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
# - {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'camera', link: ''}
- {icon: 'instagram', link: 'https://instagram.com/aproxp'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/apruski/'}
- {icon: 'envelope', link: 'mailto:aproxp@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
