# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

google-ID: 'UA-112060364-2'

menu:
- {name: 'Posts', folder: '.', file: 'posts'}
- {name: 'Photos', folder: '.', file: 'photos'}
- {name: 'About', folder: '.', file: 'about'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
# - {icon: 'twitter', link: 'https://twitter.com/paululele'}
# - {icon: 'camera', link: ''}
- {icon: 'instagram', link: 'https://instagram.com/aproxp'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/apruski/'}
- {icon: 'envelope', link: 'mailto:aproxp@gmail.com'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'
related_posts: 'You may also enjoy...'
post_date_prefix: 'Written on'
